source_list:
  - SB
  - OL
  - CP
  - ADDR


target_list:
  - RTL_TXN_FCT

s3_conf:
  s3_bucket: test-sairam-test
  staging_dir: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT
SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
      database: customers
      collection: address
CP:
  filename: KC_Extract_1_20171009.csv

REGIS_DIM:
  source_data: CP
  loading_query: >
    SELECT
      fn_uuid() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
      FROM
        CP
      WHERE
        ins_date = CURRENT_DATE
      ) CP
CHILD_DIM:
  source_data: CP
  loading_query: >
    SELECT
      fn_uuid() AS CHILD_KEY, REGIS_CNSM_ID AS CNSM_ID, REGIS_CTY_CODE AS CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_date
    FROM
      (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_date
       FROM
        CP
       WHERE
        ins_date = CURRENT_DATE
        AND CHILD_ID IS NOT NULL
      ) CP

RTL_TXN_FCT:
  source_data:
    - OL
    - SB
  source_table:
    - REGIS_DIM

  loading_query: >
    SELECT
     fn_uuid() AS RTL_TXN_KEY, CAST(TXN.SBLP_TRANSACTION_ID AS STRING)AS TXN_ID, SIZE(split(TXN.PRODUCTS, ',')) AS TXN_ITEM_QTY,
     TRANSACTION_POINT_VALUE AS TXN_LOY_VAL_STD_CCY, 0 AS TXN_GROSS_MNY_STD_CCY, TRANSACTION_RETAIL_VALUE AS TXN_GROSS_MNY_LCL_CCY,
     -1 AS MNY_LCL_CCY_TYPE_KEY, TRANSACTION_EXTERNAL_REFERENCE AS RTL_TXN_TYPE_KEY, ACTIVITY_TIMESTAMP AS TXN_TS,
     CAST(ACTIVITY_TIMESTAMP AS DATE) AS TXN_DT_KEY, HOUR(ACTIVITY_TIMESTAMP) AS TXN_TM_HOUR, MINUTE(ACTIVITY_TIMESTAMP) AS TXN_TM_MINUTE,
     SECOND(ACTIVITY_TIMESTAMP) AS TXN_TM_SECOND, '-1' AS CHNL_KEY, REG.CNSM_ID AS CNS_ID,
     "@NULL@" AS RTL_TXN_EXT_DEC_1, "@NULL@" AS RTL_TXN_EXT_DEC_2, TXN.BASE_POINT_VALUE AS
     RTL_TXN_EXT_DEC_3, MOBILE_UID AS RTL_TXN_EXT_CHAR_1, MOBILE_OS AS RTL_TXN_EXT_CHAR_2, PRODUCTS AS RTL_TXN_EXT_CHAR_3,
     RECEIPT_STATUS AS RTL_TXN_EXT_CHAR_4, CAST(MSG_CODE AS BIGINT) AS RTL_TXN_EXT_CHAR_5, TXN.ins_date AS INS_TS
    FROM
     OL TXN LEFT OUTER JOIN SB REC
     ON (TXN.SBLP_TRANSACTION_ID = REC.APP_TRANSACTION_ID )
      LEFT OUTER JOIN REGIS_DIM REG
      ON TXN.LOYALTY_ID = REG.CNSM_ID
    WHERE
     TXN.ins_date = CURRENT_DATE
     AND (TXN.ins_date = CURRENT_DATE OR TXN.ins_date is NULL )

